name: flutter_date_range_picker
description: Flutter package for selecting date ranges with input, dialog, and calendar options.
version: 0.2.0
homepage: https://github.com/GaspardMerten/date_range_picker

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  intl: '>=0.18.0 <1.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
